[package]
name = "caesar_cipher"
version = "0.0.1"
authors = ["Tom https://github.com/FeynmanTesla"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"